/*
 * File: app/store/UserSettingsStore.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('InstaSocial.store.UserSettingsStore', {
    extend: 'Ext.data.Store',
    alias: 'store.userSettingsStore',

    requires: [
        'InstaSocial.model.UserSettingModel'
    ],

    config: {
        autoLoad: true,
        data: [
            {
                id: 'networkfbstate',
                value: 0
            },
            {
                id: 'networkvkstate',
                value: 0
            }
        ],
        model: 'InstaSocial.model.UserSettingModel',
        storeId: 'UserSettingsStore'
    }
});