/*
 * File: app/view/NewsFeedContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('InstaSocial.view.NewsFeedContainer', {
    extend: 'Ext.navigation.View',
    alias: 'widget.newsFeedContainer',

    requires: [
        'InstaSocial.view.NewsFeedNavigationBarHeader',
        'InstaSocial.view.NewsFeedToolbar'
    ],

    config: {
        id: 'newsFeedContainer',
        itemId: 'newsFeedContainer',
        ui: 'dark',
        items: [
            {
                xtype: 'carousel',
                id: 'newsFeedCarousel',
                itemId: 'newsFeedCarousel'
            },
            {
                xtype: 'newsFeedToolbar'
            }
        ],
        navigationBar: {
            docked: 'top',
            id: 'newsFeedNavigationBar',
            itemId: 'newsFeedNavigationBar',
            items: [
                {
                    xtype: 'newsFeedNavigationBarHeader'
                },
                {
                    xtype: 'button',
                    align: 'right',
                    id: 'btNewsFeedRefresh',
                    itemId: 'btNewsFeedRefresh',
                    ui: 'round',
                    iconCls: 'refresh'
                }
            ]
        },
        listeners: [
            {
                fn: 'onBtNewsFeedRefreshTap',
                event: 'tap',
                delegate: '#btNewsFeedRefresh'
            }
        ]
    },

    onBtNewsFeedRefreshTap: function(button, e, eOpts) {
        if(core.connectivity.networks.fb.state == config.core.connectivity.state.loggedin){
            core.newsfeed.networks.fb.getNewsFeed();
        }
        if(core.connectivity.networks.vk.state == config.core.connectivity.state.loggedin){
            core.newsfeed.networks.vk.getNewsFeed();
        }
    }

});