/*
 * File: app/view/NewsFeedvkList.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('InstaSocial.view.NewsFeedvkList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.newsFeedvkList',

    config: {
        locked: false,
        cls: 'newsfeed-list',
        id: 'newsFeedvkList',
        itemId: 'newsFeedvkList',
        showAnimation: 'slide',
        disableSelection: true,
        deferEmptyText: false,
        scrollToTopOnRefresh: false,
        store: 'NewsFeedvkStore',
        variableHeights: true,
        scrollable: {
            direction: 'vertical',
            directionLock: true
        },
        itemTpl: Ext.create('Ext.XTemplate', 
            '<div class="newsfeed-list-item">',
            '	<div class="header">',
            '        <div class="icon">',
            '            <img src="{User.photo}"/>',
            '    	</div>',
            '        <div class="info">',
            '        	<div class="name">',
            '        		{User.full_name}',
            '    		</div>',
            '            <div class="date">',
            '                {[core.helper.getDateTimeFromUnix(values.created_time)]}',
            '    		</div>',
            '        </div>',
            '    </div>',
            '    <div class="body">',
            '        <div class="text">',
            '            {text}',
            '        </div>',
            '        {[core.renderer.attachments(values.attachments)]}',
            '    </div>',
            '    <div class="footer">',
            '        {likes_count} {[labels.lblLikes]} {comments_count} {[labels.lblComments]}',
            '    </div>',
            '</div>',
            '',
            {
                disableFormats: true
            }
        )
    },

    initialize: function() {
        this.callParent();
        this.setEmptyText(labels.lblNoData);
        this.refresh();

        var scroller = this.getScrollable().getScroller();
        scroller.on({
            scroll: function(scroller, x, y){
                if (!this.config.locked && y >= scroller.maxPosition.y - config.core.ui.newsFeedvkUpdateOffset) {
                    this.config.locked = true;
                    var newsFeedvkStore = Ext.getStore(config.stores.newsFeedvkStore);
                    var post = newsFeedvkStore.last();
                    core.newsfeed.networks.vk.getNewsFeed(null, post.data.created_time, null);
                }
            },
            maxpositionchange: function(scroller, maxPosition, eOpts){
                this.config.locked = false;
            },
            scope: this
        });

    }

});