/*
 * File: app/model/Attachment.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('InstaSocial.model.Attachment', {
    extend: 'Ext.data.Model',
    alias: 'model.attachment',

    uses: [
        'InstaSocial.model.Photo'
    ],

    config: {
        fields: [
            {
                name: 'type'
            }
        ],
        hasOne: {
            associationKey: 'photo',
            model: 'InstaSocial.model.Photo'
        }
    }
});