/*
 * File: app/model/Comment.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('InstaSocial.model.Comment', {
    extend: 'Ext.data.Model',
    alias: 'model.comment',

    uses: [
        'InstaSocial.model.User'
    ],

    config: {
        fields: [
            {
                name: 'id'
            },
            {
                name: 'comment_id'
            },
            {
                name: 'text'
            },
            {
                name: 'created_time'
            },
            {
                name: 'like_count'
            },
            {
                name: 'parent_id'
            }
        ],
        hasOne: {
            associationKey: 'user',
            model: 'InstaSocial.model.User'
        }
    }
});