/*
 * File: app/model/ParentUser.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('InstaSocial.model.ParentUser', {
    extend: 'Ext.data.Model',
    alias: 'model.parentUser',

    config: {
        fields: [
            {
                name: 'id'
            },
            {
                name: 'user_id'
            },
            {
                name: 'full_name'
            },
            {
                name: 'photo'
            },
            {
                name: 'network_id'
            }
        ]
    }
});