/*
 * File: app/model/Post.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('InstaSocial.model.Post', {
    extend: 'Ext.data.Model',
    alias: 'model.post',

    uses: [
        'InstaSocial.model.Comment',
        'InstaSocial.model.Attachment',
        'InstaSocial.model.User',
        'InstaSocial.model.ParentUser'
    ],

    config: {
        fields: [
            {
                name: 'id'
            },
            {
                name: 'post_id'
            },
            {
                name: 'text'
            },
            {
                name: 'likes_count'
            },
            {
                name: 'comments_count'
            },
            {
                name: 'reposts_count'
            },
            {
                name: 'created_time'
            },
            {
                name: 'parent_post_id'
            },
            {
                name: 'parent_created_time'
            },
            {
                name: 'type'
            },
            {
                name: 'network_id'
            }
        ],
        hasMany: [
            {
                associationKey: 'comments',
                model: 'InstaSocial.model.Comment'
            },
            {
                associationKey: 'attachments',
                model: 'InstaSocial.model.Attachment'
            }
        ],
        hasOne: [
            {
                associationKey: 'user',
                model: 'InstaSocial.model.User'
            },
            {
                associationKey: 'parent_user',
                model: 'InstaSocial.model.ParentUser'
            }
        ]
    }
});