/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('InstaSocial.controller.MainController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            menuList: '#menuList'
        },

        control: {
            "menuList": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onListItemTap: function(target) {
        console.info('MainController.onListItemTap');

        try{
            //core.newsfeed.networks.fb.getNewsFeed();
            //core.newsfeed.networks.vk.getNewsFeed();
        }catch(Exception){}


            var mainNavigationView = Ext.getCmp(config.views.mainNavigationView);
            var menuItem = record.data;

            try{
                mainNavigationView.push({
                    xtype: menuItem.link,
                    title: menuItem.name
                });
            }catch(Exception){
                console.error("Error! Unable to push the view: " + menuItem.name);
            }
    }

});